# Model configuration
model_paths:
  - "nguyenthanhdo/llama32_smol_rewrite_50k"
  - "nguyenthanhdo/llama32_smol_summarize_50k"
mode: "vector_input"
constrain_mode: "identity"

# Dataset configuration
dataset_configs:
  "/workspace/data/rewrite": 5000
  "/workspace/data/summarize": 5000
source_keys: [0, 1]
train_split: "train"
max_length: 3072

# Training parameters
output_dir: "/workspace/logits-guided-merger/results/dummy-run-2"
per_device_train_batch_size: 1
per_device_eval_batch_size: 8
gradient_accumulation_steps: 32
learning_rate: 5e-3
num_train_epochs: 3
save_steps: 100
eval_steps: 5000
logging_steps: 10
logging_dir: "/workspace/logits-guided-merger/results/dummy-run-2/logs"
eval_strategy: "steps"
report_to: "none"
remove_unused_columns: false
logging_first_step: true
bf16: true
gradient_checkpointing: false