sources:
  - model: /workspace/models/datht/llama-3b-spider-planner-fft
  - model: /workspace/models/datht/llama-3b-spider-fixed-fft

layer_range: [0, 28]
merge_method: slerp_generalized
output_dir: /workspace/models/datht/merged-test4
parameters:
  t:
    - filter: fallback_value
      value: 0.5

dtype: bfloat16