sources:
  - model: /workspace/models/Meta-Llama-3.1-8B
  - model: /workspace/models/Meta-Llama-3.1-8B-Instruct

layer_range: [0, 32]
merge_method: slerp
base_model: /workspace/models/Meta-Llama-3.1-8B
output_dir: /workspace/models/merged-test3

parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - filter: fallback_value
      value: 0.5  # Clarified fallback key

dtype: bfloat16
